name: DevOps workflow pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: |
          docker build . -t mohameda008/gademo:1.2

      - name: docker push
        run: |
          docker push mohameda008/gademo:1.2
